import { fmt } from "./number-format.js";
import { parseHolePairs, parseInstructionLines, parsePair, parseSize, parseValue } from "./parser.js";

function depths(targetDepth, stepdown) {
  const depth = -Math.abs(targetDepth);
  const passes = [];
  let z = 0;
  while (z > depth) {
    z = Math.max(z - stepdown, depth);
    passes.push(z);
  }
  return passes;
}

function header(s) {
  const plane = s.machine === "lathe" ? "G18" : "G17";
  return [
    "(Generated by Sherline G-code Assistant)",
    "(Verify clearances, work offset, tool geometry, spindle direction, and feeds before running.)",
    `${s.unitCode} G90 ${plane} G40 G49 G80 ${s.feedMode}`,
    "G54",
    `T${s.tool} M6`,
    `S${s.rpm} M3`
  ];
}

function footer(s) {
  if (s.machine === "lathe") {
    return [
      `G0 X${fmt(s.safe, s.decimals)} Z${fmt(s.safe, s.decimals)}`,
      "M5",
      "M30"
    ];
  }
  return [
    `G0 Z${fmt(s.safe, s.decimals)}`,
    "M5",
    "M30"
  ];
}

function addWarning(warnings, level, text) {
  warnings.push({ level, text });
}

export function generateMillOp(line, settings, warnings) {
  const lower = line.toLowerCase();
  const d = settings.decimals;
  const out = [`(${line})`];

  if (lower.includes("drill")) {
    const depth = parseValue(lower, ["depth", "deep", "z"]);
    const holes = parseHolePairs(lower);
    if (!depth || holes.length === 0) {
      addWarning(warnings, "critical", `Could not parse drilling command: "${line}"`);
      return out;
    }
    holes.forEach((hole) => {
      out.push(`G0 X${fmt(hole.x, d)} Y${fmt(hole.y, d)} Z${fmt(settings.safe, d)}`);
      out.push(`G1 Z-${fmt(Math.abs(depth), d)} F${fmt(settings.plunge, d)}`);
      out.push(`G0 Z${fmt(settings.safe, d)}`);
    });
    return out;
  }

  if (lower.includes("face")) {
    const size = parseSize(lower);
    const width = size ? size.width : parseValue(lower, ["width", "x"], settings.units === "inch" ? 1 : 25);
    const height = size ? size.height : parseValue(lower, ["height", "y"], settings.units === "inch" ? 1 : 25);
    const depth = parseValue(lower, ["depth", "z"], settings.units === "inch" ? 0.005 : 0.1);
    const stepover = Math.max(Math.min(width, height) / 6, settings.units === "inch" ? 0.05 : 1);
    out.push(`G0 X0 Y0 Z${fmt(settings.safe, d)}`);
    out.push(`G1 Z-${fmt(Math.abs(depth), d)} F${fmt(settings.plunge, d)}`);
    let y = 0;
    let direction = 1;
    while (y <= height + 0.000001) {
      out.push(`G1 X${fmt(direction > 0 ? width : 0, d)} Y${fmt(y, d)} F${fmt(settings.feed, d)}`);
      y += stepover;
      if (y <= height + 0.000001) out.push(`G1 Y${fmt(Math.min(y, height), d)}`);
      direction *= -1;
    }
    out.push(`G0 Z${fmt(settings.safe, d)}`);
    return out;
  }

  if (lower.includes("circle") || lower.includes("round")) {
    const diameter = parseValue(lower, ["diameter", "dia", "d"]);
    const depth = parseValue(lower, ["depth", "z"]);
    const center = parsePair(lower, 0, 0);
    if (!diameter || !depth) {
      addWarning(warnings, "critical", `Could not parse circular milling command: "${line}"`);
      return out;
    }
    const radius = diameter / 2;
    out.push(`G0 X${fmt(center.x + radius, d)} Y${fmt(center.y, d)} Z${fmt(settings.safe, d)}`);
    depths(depth, settings.stepdown).forEach((z) => {
      out.push(`G1 Z${fmt(z, d)} F${fmt(settings.plunge, d)}`);
      out.push(`G2 X${fmt(center.x + radius, d)} Y${fmt(center.y, d)} I-${fmt(radius, d)} J0 F${fmt(settings.feed, d)}`);
    });
    out.push(`G0 Z${fmt(settings.safe, d)}`);
    return out;
  }

  if (lower.includes("rectangle") || lower.includes("slot") || lower.includes("pocket")) {
    const size = parseSize(lower);
    const width = size ? size.width : parseValue(lower, ["width"]);
    const height = size ? size.height : parseValue(lower, ["height"]);
    const depth = parseValue(lower, ["depth", "z"]);
    const start = parsePair(lower, 0, 0);
    if (!width || !height || !depth) {
      addWarning(warnings, "critical", `Could not parse rectangle command: "${line}"`);
      return out;
    }
    out.push(`G0 X${fmt(start.x, d)} Y${fmt(start.y, d)} Z${fmt(settings.safe, d)}`);
    depths(depth, settings.stepdown).forEach((z) => {
      out.push(`G1 Z${fmt(z, d)} F${fmt(settings.plunge, d)}`);
      out.push(`G1 X${fmt(start.x + width, d)} F${fmt(settings.feed, d)}`);
      out.push(`G1 Y${fmt(start.y + height, d)}`);
      out.push(`G1 X${fmt(start.x, d)}`);
      out.push(`G1 Y${fmt(start.y, d)}`);
    });
    out.push(`G0 Z${fmt(settings.safe, d)}`);
    return out;
  }

  addWarning(warnings, "critical", `Unsupported mill instruction: "${line}"`);
  return out;
}

export function generateLatheOp(line, settings, warnings) {
  const lower = line.toLowerCase();
  const d = settings.decimals;
  const out = [`(${line})`];

  if (lower.includes("face")) {
    out.push(`G0 X${fmt(settings.safe, d)} Z${fmt(settings.safe, d)}`);
    out.push(`G1 Z0 F${fmt(settings.feed, d)}`);
    out.push(`G1 X0 F${fmt(settings.feed, d)}`);
    out.push(`G0 X${fmt(settings.safe, d)}`);
    return out;
  }

  if (lower.includes("turn")) {
    const diameter = parseValue(lower, ["diameter", "dia", "x"]);
    const length = parseValue(lower, ["length", "long", "z"]);
    const depth = parseValue(lower, ["depth", "stock"], diameter);
    if (!diameter || !length) {
      addWarning(warnings, "critical", `Could not parse turning command: "${line}"`);
      return out;
    }
    const startX = Math.max(diameter + Math.abs(depth), diameter + settings.stepdown);
    out.push("(Lathe X values are diameter-mode assumptions; confirm your controller setting.)");
    out.push(`G0 X${fmt(startX, d)} Z${fmt(settings.safe, d)}`);
    let x = startX;
    while (x > diameter) {
      x = Math.max(x - settings.stepdown * 2, diameter);
      out.push(`G0 X${fmt(x, d)}`);
      out.push(`G1 Z-${fmt(Math.abs(length), d)} F${fmt(settings.feed, d)}`);
      out.push(`G0 X${fmt(x + settings.stepdown * 2, d)}`);
      out.push("G0 Z0");
    }
    return out;
  }

  if (lower.includes("drill")) {
    const depth = parseValue(lower, ["depth", "deep", "z"]);
    if (!depth) {
      addWarning(warnings, "critical", `Could not parse lathe drilling command: "${line}"`);
      return out;
    }
    out.push("G0 X0");
    out.push(`G0 Z${fmt(settings.safe, d)}`);
    out.push(`G1 Z-${fmt(Math.abs(depth), d)} F${fmt(settings.plunge, d)}`);
    out.push(`G0 Z${fmt(settings.safe, d)}`);
    return out;
  }

  if (lower.includes("bore")) {
    const diameter = parseValue(lower, ["diameter", "dia", "x"]);
    const depth = parseValue(lower, ["depth", "deep", "z"]);
    if (!diameter || !depth) {
      addWarning(warnings, "critical", `Could not parse boring command: "${line}"`);
      return out;
    }
    out.push(`G0 X${fmt(diameter, d)} Z${fmt(settings.safe, d)}`);
    out.push(`G1 Z-${fmt(Math.abs(depth), d)} F${fmt(settings.feed, d)}`);
    out.push(`G0 X${fmt(Math.max(diameter - settings.stepdown, 0), d)}`);
    out.push(`G0 Z${fmt(settings.safe, d)}`);
    return out;
  }

  addWarning(warnings, "critical", `Unsupported lathe instruction: "${line}"`);
  return out;
}

export function generateProgram(instructions, settings) {
  const warnings = [
    { level: "critical", text: "Do not run this directly on a machine. Backplot, single-step in air, and verify against your Sherline controller/manual first." },
    { level: "normal", text: "Assumes G54 work offset, absolute positioning, conventional X/Y/Z mill axes, and LinuxCNC/RS274-style syntax." },
    { level: "normal", text: "Tool diameter compensation is intentionally not applied; offset your geometry or add G41/G42 only after verifying lead-in moves." }
  ];
  if (settings.machine === "lathe") {
    warnings.push({ level: "normal", text: "Lathe output assumes X is diameter mode; confirm G7/G8 behavior on your controller before cutting." });
  }

  const body = parseInstructionLines(instructions).flatMap((line) => (
    settings.machine === "lathe"
      ? generateLatheOp(line, settings, warnings)
      : generateMillOp(line, settings, warnings)
  ));

  return {
    gcode: [...header(settings), ...body, ...footer(settings)].join("\n"),
    warnings
  };
}
